
import React, { useState } from 'react';
import { Button } from '../components/Button';
import { GlassCard } from '../components/GlassCard';
import { 
  ArrowRight, ArrowLeft, Check, User, Phone, Mail, MapPin, 
  Briefcase, GraduationCap, Globe, Award, Heart, MessageSquare, 
  Wand2, Send, Camera, Info, AlertCircle 
} from 'lucide-react';
import { Screen, Template } from '../types';

interface CVFormProps {
  setScreen: (screen: Screen) => void;
  selectedTemplate: Template | null;
  onSubmitSuccess: (templateName: string) => void;
}

interface Education {
  school: string;
  degree: string;
  year: string;
}

interface Experience {
  company: string;
  role: string;
  duration: string;
  description: string;
}

export const CVForm: React.FC<CVFormProps> = ({ setScreen, selectedTemplate, onSubmitSuccess }) => {
  const [step, setStep] = useState(0);
  const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle');
  
  // Form State
  const [formData, setFormData] = useState({
    fullName: '',
    email: '',
    phonePrimary: '',
    phoneSecondary: '',
    address: '',
    birthYear: '',
    nationality: '',
    jobTitle: '',
    portfolioUrl: '',
    educations: [] as Education[],
    experiences: [] as Experience[],
    skillsTechnical: '',
    skillsTools: '',
    skillsLanguages: '',
    certifications: '',
    interestsHobbies: '',
    interestsVolunteering: '',
    references: '',
    draft: '', // Generated by AI
    message: ''
  });

  const updateField = (field: string, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  // Education Helpers
  const addEducation = () => {
    if (formData.educations.length < 3) {
      setFormData(prev => ({
        ...prev,
        educations: [...prev.educations, { school: '', degree: '', year: '' }]
      }));
    }
  };
  const updateEducation = (index: number, field: keyof Education, value: string) => {
    const newEdu = [...formData.educations];
    newEdu[index][field] = value;
    setFormData(prev => ({ ...prev, educations: newEdu }));
  };
  const removeEducation = (index: number) => {
    setFormData(prev => ({ ...prev, educations: prev.educations.filter((_, i) => i !== index) }));
  };

  // Experience Helpers
  const addExperience = () => {
    if (formData.experiences.length < 3) {
      setFormData(prev => ({
        ...prev,
        experiences: [...prev.experiences, { company: '', role: '', duration: '', description: '' }]
      }));
    }
  };
  const updateExperience = (index: number, field: keyof Experience, value: string) => {
    const newExp = [...formData.experiences];
    newExp[index][field] = value;
    setFormData(prev => ({ ...prev, experiences: newExp }));
  };
  const removeExperience = (index: number) => {
    setFormData(prev => ({ ...prev, experiences: prev.experiences.filter((_, i) => i !== index) }));
  };

  // AI Mock Generation
  const generateDraft = () => {
    // Simulation
    updateField('draft', "Génération en cours...");
    setTimeout(() => {
      updateField('draft', `Profil professionnel rigoureux et motivé, spécialisé en ${formData.jobTitle || 'gestion de projet'}. Fort de plusieurs expériences significatives, je souhaite mettre mes compétences techniques (${formData.skillsTechnical || 'N/A'}) au service d'une entreprise innovante.`);
    }, 1500);
  };

  // Validation
  const validateStep = () => {
    if (step === 1) {
      if (!formData.fullName || !formData.email) return false;
      const emailRegex = /^\S+@\S+\.\S+$/;
      if (!emailRegex.test(formData.email)) return false;
    }
    if (step === 8 && !formData.draft) return false;
    return true;
  };

  const handleNext = () => {
    if (validateStep()) {
      setStep(prev => Math.min(prev + 1, 9));
      window.scrollTo(0, 0);
    } else {
      alert("Veuillez remplir les champs obligatoires (Nom, Email) ou générer le brouillon.");
    }
  };

  const handleBack = () => {
    setStep(prev => Math.max(prev - 1, 0));
    window.scrollTo(0, 0);
  };

  // Formspree Submission
  const handleSubmit = async () => {
    setStatus('sending');

    // Formatting complex fields for the email
    const formattedEducations = formData.educations.map(e => `${e.degree} à ${e.school} (${e.year})`).join('\n');
    const formattedExperiences = formData.experiences.map(e => `${e.role} chez ${e.company} (${e.duration}): ${e.description}`).join('\n');

    const payload = {
      _subject: `Demande CV - ${selectedTemplate?.name || 'Inconnu'} - ${formData.fullName}`,
      email: formData.email,
      name: formData.fullName,
      phone: formData.phonePrimary,
      message: formData.message || "Demande de création de CV via App Mobile",
      _form_name: "cv-generator",
      model_id: selectedTemplate?.id || "N/A",
      model_name: selectedTemplate?.name || "N/A",
      birth_year: formData.birthYear,
      address: formData.address,
      phone_secondary: formData.phoneSecondary,
      nationality: formData.nationality,
      job_title: formData.jobTitle,
      portfolio_url: formData.portfolioUrl,
      educations: formattedEducations,
      experiences: formattedExperiences,
      skills_technical: formData.skillsTechnical,
      skills_tools: formData.skillsTools,
      skills_languages: formData.skillsLanguages,
      certifications: formData.certifications,
      interests_hobbies: formData.interestsHobbies,
      interests_volunteering: formData.interestsVolunteering,
      references: formData.references,
      generated_draft: formData.draft
    };

    try {
      const res = await fetch('https://formspree.io/f/mblaqgej', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(payload)
      });

      if (res.ok) {
        setStatus('success');
        setTimeout(() => {
            onSubmitSuccess(selectedTemplate?.name || 'Modèle Inconnu');
        }, 2000);
      } else {
        setStatus('error');
      }
    } catch (error) {
      setStatus('error');
    }
  };

  // Render Logic
  const renderStepContent = () => {
    switch (step) {
      case 0: // Intro
        return (
          <div className="text-center py-10">
            <div className="w-20 h-20 bg-electric-100 rounded-full flex items-center justify-center mx-auto mb-6 animate-pulse">
              <Wand2 size={40} className="text-electric-600" />
            </div>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">Création Assistée</h2>
            <p className="text-slate-600 mb-8">
              Nous allons créer votre CV <b>{selectedTemplate?.name}</b> ensemble en 10 étapes simples. 
              Préparez vos informations, nous nous occupons du design.
            </p>
            <div className="p-4 bg-blue-50 text-blue-700 rounded-xl text-sm mb-6 flex items-start gap-3 text-left">
               <Info className="shrink-0 mt-0.5" size={16} />
               <span>Une fois le formulaire terminé, nos experts recevront vos données pour finaliser votre CV professionnel.</span>
            </div>
          </div>
        );

      case 1: // Info Perso
        return (
          <div className="space-y-4">
            <h3 className="font-bold text-lg flex items-center gap-2"><User size={20} className="text-electric-500"/> Informations Personnelles</h3>
            
            <div className="grid grid-cols-1 gap-4">
              <input type="text" placeholder="Nom complet *" value={formData.fullName} onChange={e => updateField('fullName', e.target.value)} className="input-field" />
              <input type="email" placeholder="Email *" value={formData.email} onChange={e => updateField('email', e.target.value)} className="input-field" />
              <input type="tel" placeholder="Téléphone Principal" value={formData.phonePrimary} onChange={e => updateField('phonePrimary', e.target.value)} className="input-field" />
              <input type="text" placeholder="Titre du poste visé" value={formData.jobTitle} onChange={e => updateField('jobTitle', e.target.value)} className="input-field" />
              <input type="text" placeholder="Adresse / Ville" value={formData.address} onChange={e => updateField('address', e.target.value)} className="input-field" />
              <div className="grid grid-cols-2 gap-4">
                 <input type="text" placeholder="Année Naissance" value={formData.birthYear} onChange={e => updateField('birthYear', e.target.value)} className="input-field" />
                 <input type="text" placeholder="Nationalité" value={formData.nationality} onChange={e => updateField('nationality', e.target.value)} className="input-field" />
              </div>
              <input type="text" placeholder="Portfolio / LinkedIn (URL)" value={formData.portfolioUrl} onChange={e => updateField('portfolioUrl', e.target.value)} className="input-field" />
            </div>

            <div className="pt-4 border-t border-slate-100">
               <label className="block text-sm font-medium text-slate-700 mb-2">Photo Professionnelle</label>
               <a 
                 href="https://wa.me/2250170561121?text=Bonjour,%20je%20vous%20contacte%20suite%20%C3%A0%20ma%20demande%20de%20cr%C3%A9ation%20de%20CV.%20Voici%20ma%20photo%20professionnelle."
                 target="_blank"
                 rel="noreferrer"
                 className="flex items-center justify-center gap-2 w-full py-3 bg-[#25D366] text-white rounded-xl font-bold hover:bg-[#128C7E] transition-colors shadow-lg shadow-green-200"
               >
                 <Camera size={20} /> Envoyer ma photo via WhatsApp
               </a>
               <p className="text-xs text-slate-400 mt-2 text-center">La photo sera associée à votre dossier manuellement.</p>
            </div>
          </div>
        );

      case 2: // Education
        return (
          <div className="space-y-4">
            <h3 className="font-bold text-lg flex items-center gap-2"><GraduationCap size={20} className="text-electric-500"/> Formation</h3>
            <p className="text-sm text-slate-500">Ajoutez vos diplômes les plus récents (Max 3).</p>
            
            {formData.educations.map((edu, index) => (
              <div key={index} className="p-4 bg-slate-50 rounded-xl border border-slate-100 relative group">
                <button onClick={() => removeEducation(index)} className="absolute top-2 right-2 text-slate-400 hover:text-red-500"><AlertCircle size={16} /></button>
                <div className="space-y-3">
                  <input type="text" placeholder="École / Université" value={edu.school} onChange={e => updateEducation(index, 'school', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Diplôme obtenu" value={edu.degree} onChange={e => updateEducation(index, 'degree', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Année" value={edu.year} onChange={e => updateEducation(index, 'year', e.target.value)} className="input-field bg-white" />
                </div>
              </div>
            ))}

            {formData.educations.length < 3 && (
              <Button variant="secondary" onClick={addEducation} fullWidth className="border-dashed border-2">
                 + Ajouter une formation
              </Button>
            )}
          </div>
        );

      case 3: // Experience
        return (
          <div className="space-y-4">
            <h3 className="font-bold text-lg flex items-center gap-2"><Briefcase size={20} className="text-electric-500"/> Expériences</h3>
             <p className="text-sm text-slate-500">Vos expériences pro pertinentes (Max 3).</p>

            {formData.experiences.map((exp, index) => (
              <div key={index} className="p-4 bg-slate-50 rounded-xl border border-slate-100 relative">
                 <button onClick={() => removeExperience(index)} className="absolute top-2 right-2 text-slate-400 hover:text-red-500"><AlertCircle size={16} /></button>
                 <div className="space-y-3">
                  <input type="text" placeholder="Entreprise" value={exp.company} onChange={e => updateExperience(index, 'company', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Poste occupé" value={exp.role} onChange={e => updateExperience(index, 'role', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Durée (ex: 2020-2022)" value={exp.duration} onChange={e => updateExperience(index, 'duration', e.target.value)} className="input-field bg-white" />
                  <textarea placeholder="Description des tâches..." value={exp.description} onChange={e => updateExperience(index, 'description', e.target.value)} className="input-field bg-white h-24" />
                </div>
              </div>
            ))}

            {formData.experiences.length < 3 && (
              <Button variant="secondary" onClick={addExperience} fullWidth className="border-dashed border-2">
                 + Ajouter une expérience
              </Button>
            )}
          </div>
        );
      
      case 4: // Skills
        return (
          <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><Award size={20} className="text-electric-500"/> Compétences & Langues</h3>
             
             <div>
               <label className="label">Compétences Techniques (Hard Skills)</label>
               <textarea placeholder="Ex: React, Python, Gestion de projet, Comptabilité..." value={formData.skillsTechnical} onChange={e => updateField('skillsTechnical', e.target.value)} className="input-field h-20" />
             </div>
             
             <div>
               <label className="label">Outils & Logiciels</label>
               <input type="text" placeholder="Ex: Office 365, Jira, Photoshop..." value={formData.skillsTools} onChange={e => updateField('skillsTools', e.target.value)} className="input-field" />
             </div>

             <div>
               <label className="label flex items-center gap-2"><Globe size={16}/> Langues</label>
               <textarea placeholder="Ex: Français (Natif), Anglais (B2), Espagnol (Notions)..." value={formData.skillsLanguages} onChange={e => updateField('skillsLanguages', e.target.value)} className="input-field h-20" />
             </div>
          </div>
        );

      case 5: // Certifications
        return (
           <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><Award size={20} className="text-electric-500"/> Certifications</h3>
             <p className="text-sm text-slate-500">Avez-vous des certificats ou formations complémentaires ?</p>
             <textarea placeholder="Ex: Certification Google Digital Garage (2023)..." value={formData.certifications} onChange={e => updateField('certifications', e.target.value)} className="input-field h-32" />
           </div>
        );

      case 6: // Interests
        return (
           <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><Heart size={20} className="text-electric-500"/> Centres d'intérêt</h3>
             
             <div>
               <label className="label">Loisirs / Hobbies</label>
               <textarea placeholder="Ex: Football, Lecture, Voyages..." value={formData.interestsHobbies} onChange={e => updateField('interestsHobbies', e.target.value)} className="input-field h-24" />
             </div>

             <div>
               <label className="label">Bénévolat / Associatif</label>
               <textarea placeholder="Ex: Membre association XYZ..." value={formData.interestsVolunteering} onChange={e => updateField('interestsVolunteering', e.target.value)} className="input-field h-24" />
             </div>
           </div>
        );

      case 7: // References
        return (
           <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><MessageSquare size={20} className="text-electric-500"/> Références</h3>
             <p className="text-sm text-slate-500">Personnes à contacter (Optionnel).</p>
             <textarea placeholder="Nom, Poste, Téléphone/Email..." value={formData.references} onChange={e => updateField('references', e.target.value)} className="input-field h-32" />
           </div>
        );

      case 8: // AI
        return (
           <div className="space-y-6 text-center">
             <h3 className="font-bold text-lg flex items-center justify-center gap-2"><Wand2 size={20} className="text-electric-500"/> Assistant IA</h3>
             <p className="text-slate-600">Générez une ébauche de profil basée sur vos informations.</p>
             
             <div className="relative">
                <textarea 
                  value={formData.draft} 
                  onChange={e => updateField('draft', e.target.value)} 
                  className="input-field h-48 p-4 font-serif italic text-slate-600"
                  placeholder="Le texte généré apparaîtra ici..."
                />
                {!formData.draft && (
                   <div className="absolute inset-0 flex items-center justify-center bg-slate-50/50 backdrop-blur-sm rounded-xl">
                      <Button onClick={generateDraft} className="shadow-xl">
                        <Wand2 size={18} /> Générer l'ébauche
                      </Button>
                   </div>
                )}
             </div>
             <p className="text-xs text-slate-400">Vous pourrez modifier ce texte avant l'envoi.</p>
           </div>
        );

      case 9: // Submit
        return (
           <div className="space-y-6">
             <h3 className="font-bold text-lg flex items-center gap-2 text-electric-600">
               <Check size={24} /> Confirmation
             </h3>
             <div className="bg-electric-50 p-6 rounded-2xl border border-electric-100">
                <h4 className="font-bold text-slate-800 mb-2">Récapitulatif</h4>
                <ul className="space-y-2 text-sm text-slate-600">
                  <li><b>Nom:</b> {formData.fullName}</li>
                  <li><b>Email:</b> {formData.email}</li>
                  <li><b>Modèle:</b> {selectedTemplate?.name}</li>
                  <li><b>Poste:</b> {formData.jobTitle}</li>
                </ul>
             </div>
             
             <div>
               <label className="label">Message complémentaire (Optionnel)</label>
               <textarea 
                  value={formData.message}
                  onChange={e => updateField('message', e.target.value)}
                  placeholder="Instructions particulières pour notre équipe..."
                  className="input-field h-24"
               />
             </div>

             {status === 'error' && (
               <div className="p-3 bg-red-50 text-red-600 rounded-lg text-sm flex items-center gap-2">
                 <AlertCircle size={16} /> Erreur lors de l'envoi. Réessayez.
               </div>
             )}
              {status === 'success' && (
               <div className="p-3 bg-green-50 text-green-600 rounded-lg text-sm flex items-center gap-2">
                 <Check size={16} /> Demande envoyée avec succès !
               </div>
             )}
           </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="h-screen flex flex-col bg-slate-50">
      {/* Header */}
      <div className="px-4 py-4 bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-10 flex items-center justify-between">
         <button onClick={() => setScreen(Screen.DASHBOARD)} className="p-2 -ml-2 text-slate-400 hover:text-slate-600">
           <ArrowLeft size={24} />
         </button>
         <div className="flex flex-col items-center">
           <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Étape {step} / 9</span>
           <div className="w-32 h-1 bg-slate-100 rounded-full mt-1 overflow-hidden">
             <div className="h-full bg-electric-600 transition-all duration-500" style={{ width: `${(step / 9) * 100}%` }} />
           </div>
         </div>
         <div className="w-8"></div> {/* Spacer */}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 pb-32">
        <GlassCard className="min-h-[60vh]">
           {renderStepContent()}
        </GlassCard>
      </div>

      {/* Footer Actions */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-white/90 backdrop-blur-xl border-t border-slate-200 z-20 flex gap-4 max-w-md mx-auto">
         {step > 0 && (
           <Button variant="secondary" onClick={handleBack} className="flex-1">
             Retour
           </Button>
         )}
         
         {step < 9 ? (
           <Button onClick={handleNext} fullWidth={step === 0} className="flex-1">
             {step === 0 ? "Commencer" : "Suivant"} <ArrowRight size={18} />
           </Button>
         ) : (
            <Button onClick={handleSubmit} className="flex-1 bg-green-600 hover:bg-green-700 shadow-green-200" disabled={status === 'sending' || status === 'success'}>
              {status === 'sending' ? 'Envoi...' : 'Envoyer la demande'} <Send size={18} />
            </Button>
         )}
      </div>

      <style>{`
        .input-field {
          width: 100%;
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 0.75rem;
          padding: 0.875rem 1rem;
          outline: none;
          transition: all 0.2s;
          color: #334155;
        }
        .input-field:focus {
          border-color: #0ea5e9;
          box-shadow: 0 0 0 3px rgba(14, 165, 233, 0.1);
          background: white;
        }
        .label {
          display: block;
          font-size: 0.875rem;
          font-weight: 500;
          color: #475569;
          margin-bottom: 0.5rem;
        }
      `}</style>
    </div>
  );
};
