
import React, { useState, useEffect } from 'react';
import { showToast } from '../components/toast';
import { Button } from '../components/Button';
import { GlassCard } from '../components/GlassCard';
import { VersionSelector } from '../components/VersionSelector';
import { 
  ArrowRight, ArrowLeft, Check, User, Phone, Mail, MapPin, 
  Briefcase, GraduationCap, Globe, Award, Heart, MessageSquare, 
  Wand2, Send, Camera, Info, AlertCircle 
} from 'lucide-react';
import { Screen, Template, CVVersion, CVFormData, UserProfile, isProfileComplete } from '../types';
import { saveCVRequest } from '../services/supabaseClient';
import {
  saveVersion,
  hasAnyVersions,
  getVersionById
} from '../services/cvVersionService';

interface CVFormProps {
  setScreen: (screen: Screen) => void;
  selectedTemplate: Template | null;
  onSubmitSuccess: (templateName: string) => void;
  userProfile: UserProfile;
}

interface Education {
  school: string;
  degree: string;
  year: string;
}

interface Experience {
  company: string;
  role: string;
  duration: string;
  description: string;
}

export const CVForm: React.FC<CVFormProps> = ({ setScreen, selectedTemplate, onSubmitSuccess, userProfile }) => {
  const [showVersionSelector, setShowVersionSelector] = useState(false);
  const [step, setStep] = useState(0);
  const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle');
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [profileType, setProfileType] = useState('');
  const [showProfileTypeInput, setShowProfileTypeInput] = useState(false);
  
  // Form State
  const [formData, setFormData] = useState<CVFormData>({
    fullName: '',
    email: '',
    phonePrimary: '',
    phoneSecondary: '',
    address: '',
    birthYear: '',
    nationality: '',
    jobTitle: '',
    portfolioUrl: '',
    educations: [] as Education[],
    experiences: [] as Experience[],
    skillsTechnical: '',
    skillsTools: '',
    skillsLanguages: '',
    certifications: '',
    interestsHobbies: '',
    interestsVolunteering: '',
    references: '',
    draft: '', // Generated by AI
    message: ''
  });

  // Check if versions exist on mount
  useEffect(() => {
    if (step === 0 && hasAnyVersions()) {
      setShowVersionSelector(true);
    }
  }, []);

  // Prefill form from user profile on first mount
  const [didPrefill, setDidPrefill] = useState(false);
  useEffect(() => {
    if (!didPrefill && userProfile) {
      setFormData(prev => ({
        ...prev,
        fullName: userProfile.name || prev.fullName,
        email: userProfile.email || prev.email,
        phonePrimary: userProfile.phone || prev.phonePrimary,
        jobTitle: (userProfile as any).jobTitle || prev.jobTitle,
        portfolioUrl: (userProfile as any).portfolioUrl || prev.portfolioUrl,
        address: [(userProfile as any).locationCity, (userProfile as any).locationCountry].filter(Boolean).join(', ') || prev.address
      }));
      setDidPrefill(true);
    }
  }, [didPrefill, userProfile]);

  const updateField = (field: string, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  // Education Helpers
  const addEducation = () => {
    if (formData.educations.length < 3) {
      setFormData(prev => ({
        ...prev,
        educations: [...prev.educations, { school: '', degree: '', year: '' }]
      }));
    }
  };
  const updateEducation = (index: number, field: keyof Education, value: string) => {
    const newEdu = [...formData.educations];
    newEdu[index][field] = value;
    setFormData(prev => ({ ...prev, educations: newEdu }));
  };
  const removeEducation = (index: number) => {
    setFormData(prev => ({ ...prev, educations: prev.educations.filter((_, i) => i !== index) }));
  };

  // Version Management Handlers
  const handleSelectVersion = (version: CVVersion) => {
    setFormData(version.data);
    setProfileType(version.profileType);
    setShowVersionSelector(false);
    setStep(1); // Skip to actual form
  };

  const handleCreateNewVersion = () => {
    setShowVersionSelector(false);
    setShowProfileTypeInput(true);
  };

  const handleStartFormWithProfileType = () => {
    if (profileType.trim()) {
      setShowProfileTypeInput(false);
      setStep(1); // Start the form
    }
  };

  // Experience Helpers
  const addExperience = () => {
    if (formData.experiences.length < 3) {
      setFormData(prev => ({
        ...prev,
        experiences: [...prev.experiences, { company: '', role: '', duration: '', description: '' }]
      }));
    }
  };
  const updateExperience = (index: number, field: keyof Experience, value: string) => {
    const newExp = [...formData.experiences];
    newExp[index][field] = value;
    setFormData(prev => ({ ...prev, experiences: newExp }));
  };
  const removeExperience = (index: number) => {
    setFormData(prev => ({ ...prev, experiences: prev.experiences.filter((_, i) => i !== index) }));
  };

  // AI Mock Generation
  const generateDraft = () => {
    // Simulation
    updateField('draft', "Génération en cours...");
    setTimeout(() => {
      updateField('draft', `Profil professionnel rigoureux et motivé, spécialisé en ${formData.jobTitle || 'gestion de projet'}. Fort de plusieurs expériences significatives, je souhaite mettre mes compétences techniques (${formData.skillsTechnical || 'N/A'}) au service d'une entreprise innovante.`);
    }, 1500);
  };

  const handleNext = () => {
    // Step 1 Validation: Informations Personnelles
    if (step === 1) {
      const cleanEmail = formData.email.trim();
      const cleanName = formData.fullName.trim();

      if (!cleanName) {
        showToast("Le nom complet est requis pour continuer.", 'error');
        return;
      }

      // Regex robuste qui accepte les emails standards
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!cleanEmail || !emailRegex.test(cleanEmail)) {
        showToast("Adresse email invalide. Vérifiez qu'il n'y a pas d'espaces inutiles.", 'error');
        return;
      }

      // Mise à jour state avec les valeurs nettoyées (sans espaces)
      if (cleanEmail !== formData.email || cleanName !== formData.fullName) {
        setFormData(prev => ({ ...prev, email: cleanEmail, fullName: cleanName }));
      }
    }

    // Step 8 Validation: Assistant IA
    if (step === 8 && !formData.draft) {
      showToast("Cliquez sur 'Générer l'ébauche' pour créer votre profil avec l'IA.", 'info');
      return;
    }

    // Passer à l'étape suivante
    setStep(prev => Math.min(prev + 1, 9));
    window.scrollTo(0, 0);
  };

  const handleBack = () => {
    setStep(prev => Math.max(prev - 1, 0));
    window.scrollTo(0, 0);
  };

  // Submission
  const handleSubmit = async () => {
    setStatus('sending');

    // Formatting complex fields for the email
    const formattedEducations = formData.educations.map(e => `${e.degree} à ${e.school} (${e.year})`).join('\n');
    const formattedExperiences = formData.experiences.map(e => `${e.role} chez ${e.company} (${e.duration}): ${e.description}`).join('\n');

    // Payload for Formspree
    const emailPayload = {
      _subject: `Demande CV - ${selectedTemplate?.name || 'Inconnu'} - ${formData.fullName}`,
      email: formData.email,
      name: formData.fullName,
      phone: formData.phonePrimary,
      message: formData.message || "Demande de création de CV via App Mobile",
      _form_name: "cv-generator",
      model_id: selectedTemplate?.id || "N/A",
      model_name: selectedTemplate?.name || "N/A",
      birth_year: formData.birthYear,
      address: formData.address,
      phone_secondary: formData.phoneSecondary,
      nationality: formData.nationality,
      job_title: formData.jobTitle,
      portfolio_url: formData.portfolioUrl,
      educations: formattedEducations,
      experiences: formattedExperiences,
      skills_technical: formData.skillsTechnical,
      skills_tools: formData.skillsTools,
      skills_languages: formData.skillsLanguages,
      certifications: formData.certifications,
      interests_hobbies: formData.interestsHobbies,
      interests_volunteering: formData.interestsVolunteering,
      references: formData.references,
      generated_draft: formData.draft,
      profile_type: profileType // Add profile type to email
    };

    try {
      // 1. Save versioned data locally
      const savedVersion = saveVersion(profileType, formData);
      console.log('✓ CV versionnéenregistré:', savedVersion.id);

      // 2. Send to Supabase (Database)
      await saveCVRequest({
        ...formData,
        templateName: selectedTemplate?.name || 'Inconnu',
        templateId: selectedTemplate?.id,
        profileType: profileType,
        versionId: savedVersion.id
      });

      // 3. Send to Formspree (Email Notification)
      const res = await fetch('https://formspree.io/f/mblaqgej', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(emailPayload)
      });

      if (res.ok) {
        setStatus('success');
        setFormSubmitted(true);
        setStep(10);
        window.scrollTo(0, 0);
      } else {
        setStatus('error');
      }
    } catch (error) {
      console.error("Submission error:", error);
      // Even if one fails, we check logic. Here simple error status.
      setStatus('error');
    }
  };

  // Render Logic
  const renderStepContent = () => {
    // Version Selector Screen
    if (showVersionSelector) {
      return (
        <VersionSelector
          onSelectVersion={handleSelectVersion}
          onCreateNew={handleCreateNewVersion}
        />
      );
    }

    // Profile Type Input Screen
    if (showProfileTypeInput) {
      return (
        <div className="space-y-4 text-center py-10">
          <div className="w-20 h-20 bg-electric-100 rounded-full flex items-center justify-center mx-auto mb-6">
            <User size={40} className="text-electric-600" />
          </div>
          <h2 className="text-2xl font-bold text-slate-800">Quel type de profil créez-vous ?</h2>
          <p className="text-slate-600">
            Cette classification vous permettra de réutiliser vos données pour plusieurs CV.
          </p>
          
          <div className="space-y-3 mt-6">
            <input
              type="text"
              placeholder="Ex: DEV, COMMERCIAL, DESIGNER, JUNIOR..."
              value={profileType}
              onChange={e => setProfileType(e.target.value.toUpperCase())}
              className="input-field text-center text-lg font-semibold"
              onKeyPress={e => e.key === 'Enter' && handleStartFormWithProfileType()}
              autoFocus
            />
            <p className="text-sm text-slate-500">Entrez un mot-clé qui décrit votre profil professionnel.</p>
          </div>
        </div>
      );
    }

    switch (step) {
      case 0: // Intro
        return (
          <div className="text-center py-10">
            <div className="w-20 h-20 bg-electric-100 rounded-full flex items-center justify-center mx-auto mb-6 animate-pulse">
              <Wand2 size={40} className="text-electric-600" />
            </div>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">Création Assistée</h2>
            <p className="text-slate-600 mb-8">
              Nous allons créer votre CV <b>{selectedTemplate?.name}</b> ensemble en 10 étapes simples. 
              Préparez vos informations, nous nous occupons du design.
            </p>
            <div className="p-4 bg-blue-50 text-blue-700 rounded-xl text-sm mb-6 flex items-start gap-3 text-left">
               <Info className="shrink-0 mt-0.5" size={16} />
               <span>Une fois le formulaire terminé, nos experts recevront vos données pour finaliser votre CV professionnel.</span>
            </div>
          </div>
        );

      case 1: // Info Perso
        return (
          <div className="space-y-4">
            <h3 className="font-bold text-lg flex items-center gap-2"><User size={20} className="text-electric-500"/> Informations Personnelles</h3>
            
            <div className="grid grid-cols-1 gap-4">
              <input type="text" placeholder="Nom complet *" value={formData.fullName} onChange={e => updateField('fullName', e.target.value)} className="input-field" />
              <input type="email" placeholder="Email *" value={formData.email} onChange={e => updateField('email', e.target.value)} className="input-field" />
              <input type="tel" placeholder="Téléphone Principal" value={formData.phonePrimary} onChange={e => updateField('phonePrimary', e.target.value)} className="input-field" />
              <input type="text" placeholder="Titre du poste visé" value={formData.jobTitle} onChange={e => updateField('jobTitle', e.target.value)} className="input-field" />
              <input type="text" placeholder="Côte d'Ivoire, Abidjan" value={formData.address} onChange={e => updateField('address', e.target.value)} className="input-field" />
              <div className="grid grid-cols-2 gap-4">
                 <input type="text" placeholder="Année Naissance" value={formData.birthYear} onChange={e => updateField('birthYear', e.target.value)} className="input-field" />
                 <input type="text" placeholder="Nationalité" value={formData.nationality} onChange={e => updateField('nationality', e.target.value)} className="input-field" />
              </div>
              <input type="text" placeholder="Portfolio / LinkedIn (URL)" value={formData.portfolioUrl} onChange={e => updateField('portfolioUrl', e.target.value)} className="input-field" />
            </div>
          </div>
        );

      case 2: // Education
        return (
          <div className="space-y-4">
            <h3 className="font-bold text-lg flex items-center gap-2"><GraduationCap size={20} className="text-electric-500"/> Formation</h3>
            <p className="text-sm text-slate-500">Ajoutez vos diplômes les plus récents (Max 3).</p>
            
            {formData.educations.map((edu, index) => (
              <div key={index} className="p-4 bg-slate-50 rounded-xl border border-slate-100 relative group">
                <button onClick={() => removeEducation(index)} className="absolute top-2 right-2 text-slate-400 hover:text-red-500"><AlertCircle size={16} /></button>
                <div className="space-y-3">
                  <input type="text" placeholder="École / Université" value={edu.school} onChange={e => updateEducation(index, 'school', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Diplôme obtenu" value={edu.degree} onChange={e => updateEducation(index, 'degree', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Année" value={edu.year} onChange={e => updateEducation(index, 'year', e.target.value)} className="input-field bg-white" />
                </div>
              </div>
            ))}

            {formData.educations.length < 3 && (
              <Button variant="secondary" onClick={addEducation} fullWidth className="border-dashed border-2">
                 + Ajouter une formation
              </Button>
            )}
          </div>
        );

      case 3: // Experience
        return (
          <div className="space-y-4">
            <h3 className="font-bold text-lg flex items-center gap-2"><Briefcase size={20} className="text-electric-500"/> Expériences</h3>
             <p className="text-sm text-slate-500">Vos expériences pro pertinentes (Max 3).</p>

            {formData.experiences.map((exp, index) => (
              <div key={index} className="p-4 bg-slate-50 rounded-xl border border-slate-100 relative">
                 <button onClick={() => removeExperience(index)} className="absolute top-2 right-2 text-slate-400 hover:text-red-500"><AlertCircle size={16} /></button>
                 <div className="space-y-3">
                  <input type="text" placeholder="Entreprise" value={exp.company} onChange={e => updateExperience(index, 'company', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Poste occupé" value={exp.role} onChange={e => updateExperience(index, 'role', e.target.value)} className="input-field bg-white" />
                  <input type="text" placeholder="Durée (ex: 2020-2022)" value={exp.duration} onChange={e => updateExperience(index, 'duration', e.target.value)} className="input-field bg-white" />
                  <textarea placeholder="Description des tâches..." value={exp.description} onChange={e => updateExperience(index, 'description', e.target.value)} className="input-field bg-white h-24" />
                </div>
              </div>
            ))}

            {formData.experiences.length < 3 && (
              <Button variant="secondary" onClick={addExperience} fullWidth className="border-dashed border-2">
                 + Ajouter une expérience
              </Button>
            )}
          </div>
        );
      
      case 4: // Skills
        return (
          <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><Award size={20} className="text-electric-500"/> Compétences & Langues</h3>
             
             <div>
               <label className="label">Compétences Techniques (Hard Skills)</label>
               <textarea placeholder="Ex: React, Python, Gestion de projet, Comptabilité..." value={formData.skillsTechnical} onChange={e => updateField('skillsTechnical', e.target.value)} className="input-field h-20" />
             </div>
             
             <div>
               <label className="label">Outils & Logiciels</label>
               <input type="text" placeholder="Ex: Office 365, Jira, Photoshop..." value={formData.skillsTools} onChange={e => updateField('skillsTools', e.target.value)} className="input-field" />
             </div>

             <div>
               <label className="label flex items-center gap-2"><Globe size={16}/> Langues</label>
               <textarea placeholder="Ex: Français (Natif), Anglais (B2), Espagnol (Notions)..." value={formData.skillsLanguages} onChange={e => updateField('skillsLanguages', e.target.value)} className="input-field h-20" />
             </div>
          </div>
        );

      case 5: // Certifications
        return (
           <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><Award size={20} className="text-electric-500"/> Certifications</h3>
             <p className="text-sm text-slate-500">Avez-vous des certificats ou formations complémentaires ?</p>
             <textarea placeholder="Ex: Certification Google Digital Garage (2023)..." value={formData.certifications} onChange={e => updateField('certifications', e.target.value)} className="input-field h-32" />
           </div>
        );

      case 6: // Interests
        return (
           <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><Heart size={20} className="text-electric-500"/> Centres d'intérêt</h3>
             
             <div>
               <label className="label">Loisirs / Hobbies</label>
               <textarea placeholder="Ex: Football, Lecture, Voyages..." value={formData.interestsHobbies} onChange={e => updateField('interestsHobbies', e.target.value)} className="input-field h-24" />
             </div>

             <div>
               <label className="label">Bénévolat / Associatif</label>
               <textarea placeholder="Ex: Membre association XYZ..." value={formData.interestsVolunteering} onChange={e => updateField('interestsVolunteering', e.target.value)} className="input-field h-24" />
             </div>
           </div>
        );

      case 7: // References
        return (
           <div className="space-y-4">
             <h3 className="font-bold text-lg flex items-center gap-2"><MessageSquare size={20} className="text-electric-500"/> Références</h3>
             <p className="text-sm text-slate-500">Personnes à contacter (Optionnel).</p>
             <textarea placeholder="Nom, Poste, Téléphone/Email..." value={formData.references} onChange={e => updateField('references', e.target.value)} className="input-field h-32" />
           </div>
        );

      case 8: // AI
        return (
           <div className="space-y-6 text-center">
             <h3 className="font-bold text-lg flex items-center justify-center gap-2"><Wand2 size={20} className="text-electric-500"/> Assistant IA</h3>
             <p className="text-slate-600">Générez une ébauche de profil basée sur vos informations.</p>
             
             <div className="relative">
                <textarea 
                  value={formData.draft} 
                  onChange={e => updateField('draft', e.target.value)} 
                  className="input-field h-48 p-4 font-serif italic text-slate-600"
                  placeholder="Le texte généré apparaîtra ici..."
                />
                {!formData.draft && (
                   <div className="absolute inset-0 flex items-center justify-center bg-slate-50/50 backdrop-blur-sm rounded-xl">
                      <Button onClick={generateDraft} type="button" className="shadow-xl">
                        <Wand2 size={18} /> Générer l'ébauche
                      </Button>
                   </div>
                )}
             </div>
             <p className="text-xs text-slate-400">Vous pourrez modifier ce texte avant l'envoi.</p>
           </div>
        );

      case 9: // Submit
        return (
           <div className="space-y-6">
             <h3 className="font-bold text-lg flex items-center gap-2 text-electric-600">
               <Check size={24} /> Confirmation
             </h3>
             <div className="bg-electric-50 p-6 rounded-2xl border border-electric-100">
                <h4 className="font-bold text-slate-800 mb-2">Récapitulatif</h4>
                <ul className="space-y-2 text-sm text-slate-600">
                  <li><b>Nom:</b> {formData.fullName}</li>
                  <li><b>Email:</b> {formData.email}</li>
                  <li><b>Modèle:</b> {selectedTemplate?.name}</li>
                  <li><b>Poste:</b> {formData.jobTitle}</li>
                </ul>
             </div>
             
             <div>
               <label className="label">Message complémentaire (Optionnel)</label>
               <textarea 
                  value={formData.message}
                  onChange={e => updateField('message', e.target.value)}
                  placeholder="Instructions particulières pour notre équipe..."
                  className="input-field h-24"
               />
             </div>

             {status === 'error' && (
               <div className="p-3 bg-red-50 text-red-600 rounded-lg text-sm flex items-center gap-2">
                 <AlertCircle size={16} /> Erreur lors de l'envoi. Réessayez.
               </div>
             )}
           </div>
        );

      case 10: // Photo Upload - After successful submission
        return (
           <div className="space-y-6">
             <h3 className="font-bold text-lg flex items-center gap-2 text-electric-600">
               <Check size={24} /> Demande Envoyée !
             </h3>
             <div className="bg-green-50 p-6 rounded-2xl border border-green-200">
               <p className="text-green-700 font-semibold mb-2">✓ Votre demande de CV a été reçue avec succès.</p>
               <p className="text-sm text-green-600">Nous allons examiner vos informations et préparer votre CV personnalisé.</p>
             </div>
             
             {!isProfileComplete(userProfile) && (
               <div className="bg-yellow-50 p-4 rounded-2xl border border-yellow-200">
                 <p className="text-yellow-700 font-semibold mb-2">⚠️ Complétez votre profil</p>
                 <p className="text-sm text-yellow-600 mb-3">Pour une meilleure expérience, veuillez compléter vos informations personnelles dans l'espace compte.</p>
               </div>
             )}
             
             <div className="pt-6 border-t border-slate-100">
               <label className="block text-sm font-medium text-slate-700 mb-4">Étape suivante : Votre photo professionnelle</label>
               <p className="text-sm text-slate-600 mb-4">Pour finaliser votre CV, envoyez-nous votre photo professionnelle via WhatsApp. Elle sera intégrée à votre dossier.</p>
               <a 
                 href="https://wa.me/2250170561121?text=Bonjour,%20je%20vous%20contacte%20suite%20%C3%A0%20ma%20demande%20de%20cr%C3%A9ation%20de%20CV.%20Voici%20ma%20photo%20professionnelle."
                 target="_blank"
                 rel="noreferrer"
                 className="flex items-center justify-center gap-2 w-full py-3 bg-[#25D366] text-white rounded-xl font-bold hover:bg-[#128C7E] transition-colors shadow-lg shadow-green-200"
               >
                 <Camera size={20} /> Envoyer ma photo via WhatsApp
               </a>
               <p className="text-xs text-slate-400 mt-3 text-center">La photo sera associée à votre dossier manuellement.</p>
             </div>
           </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="w-full min-h-screen flex flex-col bg-slate-50">
      {/* Header */}
      <div className="px-4 py-4 bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-10 flex items-center justify-between">
         <button onClick={() => setScreen(Screen.DASHBOARD)} className="p-2 -ml-2 text-slate-400 hover:text-slate-600">
           <ArrowLeft size={24} />
         </button>
         <div className="flex flex-col items-center">
           {!showVersionSelector && !showProfileTypeInput && (
             <>
               {step !== 10 ? (
                 <>
                   <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Étape {step} / 9</span>
                   <div className="w-32 h-1 bg-slate-100 rounded-full mt-1 overflow-hidden">
                     <div className="h-full bg-electric-600 transition-all duration-500" style={{ width: `${(step / 9) * 100}%` }} />
                   </div>
                 </>
               ) : (
                 <span className="text-xs font-bold text-green-600 uppercase tracking-widest">✓ Complété</span>
               )}
             </>
           )}
           {showVersionSelector && <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Vos Versions</span>}
           {showProfileTypeInput && <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Type de Profil</span>}
         </div>
         <div className="w-8"></div> {/* Spacer */}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 pb-32">
        <GlassCard className="min-h-[60vh]">
           {renderStepContent()}
        </GlassCard>
      </div>

      {/* Footer Actions */}
      <div className="fixed bottom-0 left-0 right-0 p-2 bg-white/90 backdrop-blur-xl border-t border-slate-200 z-20 flex justify-center" style={{ width: '100%' }}>
        <div className="flex gap-2 w-full max-w-xs">
         {showProfileTypeInput && (
           <>
             <Button variant="secondary" onClick={() => setShowProfileTypeInput(false)} type="button" className="flex-1 py-1.5 px-2 text-xs">
               Retour
             </Button>
             <Button 
               onClick={handleStartFormWithProfileType} 
               type="button" 
               className="flex-1 py-1.5 px-2 text-xs"
               disabled={!profileType.trim()}
             >
               Continuer
             </Button>
           </>
         )}
         
         {!showVersionSelector && !showProfileTypeInput && (
           <>
             {step > 0 && step !== 10 && (
               <Button variant="secondary" onClick={handleBack} type="button" className="flex-1 py-1.5 px-2 text-xs">
                 Retour
               </Button>
             )}
             
             {step < 9 ? (
               <Button onClick={handleNext} type="button" className="flex-1 py-1.5 px-2 text-xs">
                 {step === 0 ? "Commencer" : "Suivant"}
               </Button>
             ) : step === 9 ? (
                <Button onClick={handleSubmit} type="button" className="flex-1 py-1.5 px-2 text-xs bg-green-600 hover:bg-green-700" disabled={status === 'sending'}>
                  {status === 'sending' ? 'Envoi...' : 'Envoyer'}
                </Button>
             ) : step === 10 ? (
               <div className="flex gap-2 w-full flex-col">
                 {!isProfileComplete(userProfile) && (
                   <Button 
                     onClick={() => {
                       showToast('Veuillez compléter votre profil pour continuer', 'info');
                       setScreen(Screen.SETTINGS);
                     }} 
                     type="button" 
                     className="flex-1 py-1.5 px-2 text-xs bg-yellow-600 hover:bg-yellow-700"
                   >
                     Compléter le profil
                   </Button>
                 )}
                 <Button 
                   onClick={() => {
                     onSubmitSuccess(selectedTemplate?.name || 'Modèle Inconnu');
                     setScreen(Screen.DASHBOARD);
                   }} 
                   type="button" 
                   className="flex-1 py-1.5 px-2 text-xs"
                 >
                   Retour au Tableau de Bord
                 </Button>
               </div>
             ) : null}
           </>
         )}
        </div>
      </div>

      <style>{`
        .input-field {
          width: 100%;
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 0.75rem;
          padding: 0.875rem 1rem;
          outline: none;
          transition: all 0.2s;
          color: #334155;
        }
        .input-field:focus {
          border-color: #0ea5e9;
          box-shadow: 0 0 0 3px rgba(14, 165, 233, 0.1);
          background: white;
        }
        .label {
          display: block;
          font-size: 0.875rem;
          font-weight: 500;
          color: #475569;
          margin-bottom: 0.5rem;
        }
      `}</style>
    </div>
  );
};
